#!/bin/bash
#wget dulu ya guys hehe
wget https://raw.githubusercontent.com/AlawiStore24/domain/main/domain.sh
clear
#pindah ke /usr/bin/
mv domain.sh /usr/bin/alawi
clear
#izin aksesnya
cd /usr/bin/
chmod +x alawi
clear
#kembali ke root
cd
rm -rf pointing
clear
#tes pointing
pointing
clear
